// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmWgknNHbtvuNWAvJwDSGhHn8NIbgN8xs',
    appId: '1:243170326940:web:0e910e83eb59942ff7b059',
    messagingSenderId: '243170326940',
    projectId: 'flutter-firebase-app-440c1',
    authDomain: 'flutter-firebase-app-440c1.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-440c1.firebasestorage.app',
    measurementId: 'G-L2FHEEEYYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABkYyaw9W9QfJzcQ2A9_EQRjcUrY5uRd4',
    appId: '1:243170326940:android:7b42af2615f9d1a3f7b059',
    messagingSenderId: '243170326940',
    projectId: 'flutter-firebase-app-440c1',
    storageBucket: 'flutter-firebase-app-440c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoo-ijnrgVulPuz5IrapGSoL1TsY9uTRQ',
    appId: '1:243170326940:ios:8c2bcef1b95a95b4f7b059',
    messagingSenderId: '243170326940',
    projectId: 'flutter-firebase-app-440c1',
    storageBucket: 'flutter-firebase-app-440c1.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase85',
  );
}
